name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Adjust to your Python version

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt  # Adjust if your requirements file is named differently

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest  # Run your tests here